max_jobs: 1

image: Visual Studio 2015

environment:
  matrix:
#  - Toolset: v141
  - Toolset: v140
  - Toolset: v120
  - Toolset: v110
  - Toolset: v100

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

build:
  verbosity: minimal
  project: mdbx.sln

test_script:
- ps: |
    if (($env:PLATFORM -eq "x86") -and (Test-Path "C:\projects\libmdbx\Win32\$env:CONFIGURATION\test.exe" -PathType Leaf)) {
      & "C:\projects\libmdbx\Win32\$env:CONFIGURATION\test.exe" --pathname=tmp.db --basic --dont-cleanup-after
    } else {
      & "C:\projects\libmdbx\$env:PLATFORM\$env:CONFIGURATION\test.exe" --pathname=tmp.db --basic --dont-cleanup-after
    }
